project:
  type: website
  output-dir: docs
  resources:
    - "Mattioli_CV.pdf"
    - "blog/**/*.pdf"
    - "projects/**/*.pdf"

website:
  site-url: "https://lormatt.github.io"
  cookie-consent: true
  bread-crumbs: true
  title: "Lorenzo Mattioli"
  navbar:
    style: docked
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Projects
        href: projects.qmd
      - text: Publications
        href: Publications.qmd
      - text: About
        href: about.qmd
    right:
      - icon: instagram
        href: https://www.instagram.com/ermattaraus/
      - icon: github
        href: https://github.com/lorMatt
      - icon: envelope
        href: mailto:lorenzo.mattioli5@studio.unibo.it
format:
  html:
    embed-resources: true
    theme: simplex
    css: styles.css

execute:
  freeze: auto
  
editor: visual

